
import styled from "styled-components";

export const Button = styled.button`
  align-items: center;
  appearance: none;
  background-color: rgba(0, 0, 0, 0);
  border: 0px none rgb(255, 255, 255);
  border-radius: 3px;
  box-shadow: none;
  box-sizing: border-box;
  color: rgb(255, 255, 255);
  color-scheme: light;
  cursor: pointer;
  display: flex;
  font-feature-settings: normal;
  font-kerning: auto;
  font-optical-sizing: auto;
  font-size: 14px;
  font-stretch: 100%;
  font-style: normal;
  font-variant-alternates: normal;
  font-variant-caps: normal;
  font-variant-east-asian: normal;
  font-variant-ligatures: normal;
  font-variant-numeric: normal;
  font-variant-position: normal;
  font-variation-settings: normal;
  font-weight: 700;
  height: 32px;
  justify-content: center;
  letter-spacing: normal;
  line-height: 32px;
  margin: 0px;
  overflow-x: visible;
  overflow-y: visible;
  padding-block-end: 0px;
  padding-block-start: 0px;
  padding-inline-end: 0px;
  padding-inline-start: 0px;
  padding: 0px;
  position: relative;
  text-align: center;
  text-decoration-color: rgb(255, 255, 255);
  text-decoration-line: none;
  text-decoration-style: solid;
  text-decoration-thickness: auto;
  text-indent: 0px;
  text-rendering: auto;
  text-shadow: none;
  text-size-adjust: 100%;
  text-transform: none;
  text-wrap: nowrap;
  transition-duration: 0.085s;
  transition-property: background-color, border-color, box-shadow;
  transition-timing-function: ease;
  white-space-collapse: collapse;
  word-spacing: 0px;
  -webkit-border-image: none;
`;
